/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DesaGUI;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Danil Pratama
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
    }
    
    private javax.swing.JRadioButton kepalaDesaRadioButton;
    private javax.swing.JRadioButton sekretarisRadioButton;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        status = new javax.swing.JComboBox<>();
        submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(88, 180, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 40));

        jTextField1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jTextField1.setText("PENGELOLAAN KEUANGAN DESA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 40);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jTextField7.setText("LOGIN");
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 21, 71, -1));

        jTextField2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jTextField2.setText("Username");
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 75, 71, -1));

        jTextField3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jTextField3.setText("Password");
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 115, 71, -1));

        jTextField4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jTextField4.setText("Status");
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 155, 71, -1));

        username.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 75, 100, -1));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 115, 100, -1));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kepala Desa", "Sekretaris" }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel3.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 155, -1, -1));

        submit.setBackground(new java.awt.Color(255, 0, 0));
        submit.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel3.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 195, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Tiga Wilayah di Bengkulu Belum Cairkan Dana Desa, Kok Bisa_ (1).jpeg"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 6, 400, 260));

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 40, 400, 260);

        setSize(new java.awt.Dimension(414, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // Get the entered username, password, and status
        String enteredUsername = username.getText();
        String enteredPassword = new String(password.getPassword());
        String selectedStatus = (String) status.getSelectedItem();
        
        // Example user data for Kepala Desa and Sekretaris
        String KepalaDesaUsername = "danil"; // Example username for Kepala Desa
        String KepalaDesaPassword = "2323"; // Example password for Kepala Desa
         
        String SekretarisUsername = "bilo"; // Example username for Sekretaris
        String SekretarisPassword = "4444"; // Example password for Sekretaris
        Object kepalaDesaPassword = KepalaDesaPassword;
        Object kepalaDesaUsername = KepalaDesaUsername;
        Object sekretarisPassword = SekretarisPassword;
        Object sekretarisUsername = SekretarisUsername;
        
        // Check credentials for Kepala Desa or Sekretaris
        if (selectedStatus.equals("Kepala Desa") && enteredUsername.equals(kepalaDesaUsername) && enteredPassword.equals(kepalaDesaPassword)) {
            // If login is successful, open KepalaDesa GUI
            JOptionPane.showMessageDialog(this, "Login Successful as Kepala Desa!");
            new KepalaDesa().setVisible(true);
            this.dispose(); // Close the login window
            
        } else if (selectedStatus.equals("Sekretaris") && enteredUsername.equals(SekretarisUsername) && enteredPassword.equals(SekretarisPassword)) {
            // If login is successful, open SekretarisDesa GUI
            JOptionPane.showMessageDialog(this, "Login Successful as Sekretaris!");
            try {
                SekretarisDesa sekretarisDesa = new SekretarisDesa();  // Create SekretarisDesa instance
                sekretarisDesa.setVisible(true);  // Show SekretarisDesa window
                this.dispose(); // Close the login window
            } catch (Exception ex) {
                Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        } else {
            // If credentials are incorrect
            JOptionPane.showMessageDialog(this, "Invalid Username, Password, or Status!", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
        String rolePengguna = "";
        if (kepalaDesaRadioButton.isSelected()) {
            rolePengguna = "kepalaDesa";
        } else if (sekretarisRadioButton.isSelected()) {
            rolePengguna = "sekretaris";
        }
        // Pastikan rolePengguna sudah terisi
        if (!rolePengguna.isEmpty()) {
            System.out.println("Role Pengguna (Login): " + rolePengguna);  // Debugging
            new Riwayat(rolePengguna).setVisible(true);
            this.dispose(); // Tutup halaman login setelah berpindah ke Riwayat
        } else {
            JOptionPane.showMessageDialog(this, "Pilih peran pengguna", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JButton submit;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
